name: 'Monday Mona'
description: 'Monday Mona Writeback'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  MONDAY_TOKEN:
    description: 'Monday API token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'